/**
 * LinkedIn Platform Publisher
 */

/**
 * Fetches the user's unique LinkedIn Person URN using their access token.
 */
async function getAuthorUrn(token) {
  const res = await fetch('https://api.linkedin.com/v2/userinfo', {
    headers: {
      'Authorization': `Bearer ${token}`
    }
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to fetch LinkedIn profile: ${res.status} ${errorText}`);
  }

  const data = await res.json();
  // The 'sub' field in userinfo contains the unique member ID
  return `urn:li:person:${data.sub}`;
}

/**
 * Publishes a text post to the user's LinkedIn feed.
 * 
 * @param {Object} articleData The JSON object generated by Gemini
 */
async function publishToLinkedIn(articleData) {
  const token = process.env.LINKEDIN_ACCESS_TOKEN;
  if (!token) {
    console.log('No LINKEDIN_ACCESS_TOKEN found. Skipping LinkedIn publish.');
    return;
  }

  const postText = articleData.linkedin_post;
  if (!postText) {
    console.log('No linkedin_post content generated by AI. Skipping LinkedIn publish.');
    return;
  }

  try {
    console.log('Publishing to LinkedIn...');

    // 1. Get the Author URN
    const authorUrn = await getAuthorUrn(token);

    // 2. Publish the post
    const res = await fetch('https://api.linkedin.com/v2/ugcPosts', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-Restli-Protocol-Version': '2.0.0'
      },
      body: JSON.stringify({
        author: authorUrn,
        lifecycleState: 'PUBLISHED',
        specificContent: {
          'com.linkedin.ugc.ShareContent': {
            shareCommentary: {
              text: postText
            },
            shareMediaCategory: 'NONE'
          }
        },
        visibility: {
          'com.linkedin.ugc.MemberNetworkVisibility': 'PUBLIC'
        }
      })
    });

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`LinkedIn API Error: ${res.status} ${errorText}`);
    }

    const data = await res.json();
    console.log('✅ Successfully published the article to LinkedIn!');
    console.log(`LinkedIn Post ID: ${data.id}`);

  } catch (error) {
    console.error('An error occurred while publishing to LinkedIn:');
    console.error(error.message);
    process.exit(1);
  }
}

module.exports = {
  publishToLinkedIn
};
