export * from "./async";
export * from "./browser";
export * from "./dom";
export * from "./state";
export * from "./time";
import { useAsync, useAsyncDebounce, useDebounce, useThrottle } from "./async";
import { useLocalStorage, useSessionStorage } from "./browser";
import { useClickOutside, useElementSize, useIntersectionObserver, useResizeObserver, useWidth } from "./dom";
import { useBoolean, useCounter, usePrevious, useToggle } from "./state";
import { useInterval, useTimeout } from "./time";
declare const _default: {
    useAsync: typeof useAsync;
    useAsyncDebounce: typeof useAsyncDebounce;
    useDebounce: typeof useDebounce;
    useThrottle: typeof useThrottle;
    useClipboard: (timeout?: number) => {
        copied: boolean;
        error: Error | null;
        copy: (text: string) => Promise<boolean>;
    };
    useLocalStorage: typeof useLocalStorage;
    useOnlineStatus: () => boolean;
    useSessionStorage: typeof useSessionStorage;
    useClickOutside: typeof useClickOutside;
    useElementSize: typeof useElementSize;
    useIntersectionObserver: typeof useIntersectionObserver;
    useResizeObserver: typeof useResizeObserver;
    useWidth: typeof useWidth;
    useBoolean: typeof useBoolean;
    useCounter: typeof useCounter;
    usePrevious: typeof usePrevious;
    useToggle: typeof useToggle;
    useInterval: typeof useInterval;
    useTimeout: typeof useTimeout;
};
export default _default;
